INSERT INTO `USER` (CREATED_AT, NAME, PASSWORD, PROFILE) VALUES (NOW(), 'ADMIN', 'ADMIN', 'ADMIN');
INSERT INTO `USER_EMAILS` (ID, EMAIL) VALUES (1, 'abc@123.com');
INSERT INTO `USER_EMAILS` (ID, EMAIL) VALUES (1, 'aaa@bbb.com.br');
INSERT INTO `BANK` (CODE, NAME) VALUES ('001', 'Banco do Brasil');